name: CI-Arduino-Esp32
on: [workflow_dispatch, push]


jobs:
  Arduino-ESP32:
    runs-on: ubuntu-latest
    env:
      TARGET: esp32wrover
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        curl https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json --output /home/runner/.arduino15/package_esp32_index.json
        arduino-cli core install -v esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli lib install -v ArduinoJson
        arduino-cli lib install -v --git-url https://github.com/axcap/Esp-GitHub-OTA.git

    - name: Compile Sketch
      run: arduino-cli compile -b esp32:esp32:${{ env.TARGET }}
      working-directory: examples/ESP32_example